name: Daily Stock Brief

on:
  workflow_dispatch:

  schedule:
    - cron: '0 8 * * 1-5'
    
jobs:

  run:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v5

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Show files
        run: |
          pwd
          ls -la

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Run script
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

        run: |
          python daily_brief.py
